spring.application.name=sb-ecomm

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb

project.image=images/

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.hibernate.ddl-auto=update

spring.app.jwtSecret=mySecretKey123kljdfglif85oijhjk3753uhjff893kjh4389rhjjh3489rjhkfo3734hj
spring.app.jwtExpirationInMs=3600000
spring.ecom.app.jwtCookieName=sb-ecomm-jwt

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.echapps.ecom.project=DEBUG
