spring.application.name=sb-ecomm

# H2 Database configuration
#spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
#spring.datasource.url=${H2_DATASOURCE_URL}

# MySQL Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

# PostgreSQL Database configuration
#spring.datasource.url=${POSTGRES_DATASOURCE_URL}
#spring.datasource.username=${POSTGRES_DATASOURCE_USERNAME}
#spring.datasource.password=${POSTGRES_DATASOURCE_PASSWORD}
#spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

project.image=${PROJECT_IMAGE_DIR}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate DDL auto configuration (needed for any db other than H2)
spring.jpa.hibernate.ddl-auto=update

spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationInMs=${JWT_EXPIRATION_MS}
spring.ecom.app.jwtCookieName=${JWT_COOKIE_NAME}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.echapps.ecom.project=DEBUG
